### ISSUE TITLE
[LinesCounter] Внезапно, чтение файла

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#2]
``` C#
do
{
   str = file.ReadLine();
   //...
}
```

Эта конструкция падает при определенных условиях. При каких? И как надо правильно?

**Comment by dzhana2** [comment]
А вот тут я очень глупая, потому что не знаю, в чем проблема. readLine может вернуть null, но это дальше обрабатывается.
Может проблемы возникнут, если у нас как-то резко права на чтение файла отберут или удалят его? Добавить что-то вроде Peek, чтобы проверять перед каждой попыткой считать строку?

**Comment by pavel-b-novikov** [comment]
Ну только не Peek наверное, а там специальная проперть есть с очень говорящим названием.

**Comment by pavel-b-novikov** [comment]
...кстати на которое можно поставить while

**Comment by dzhana2** [comment]
Exists?

**Comment by dzhana2** [comment]
А, или EndOfStream

**Comment by pavel-b-novikov** [comment]
Ну вот же! Вы сами все знаете :)

**Comment by pavel-b-novikov** [comment]
Давайте доделывайте, чтобы сегодня я смог выставить все зачеты

**Comment by dzhana2** [comment]
Исправлено.

**Comment by pavel-b-novikov** [comment]
``` C#
 while (!file.EndOfStream)
                {
                    if (!File.Exists(fileName))
                    {
                        Console.WriteLine("File {0} suddenly unavailable. The result of calculation may be wrong.", fileName);
                        break;
                    }
```

ну и что это за сюрреализм?
SUDDENLY, ага

**Comment by dzhana2** [comment]
Убрала if

**Comment by pavel-b-novikov** [comment]
То-то же.
Правда и сообщение на консоль тоже убрала. И обработку этой ситуации...
Но я не хочу быть брюзгой и придираться к таким мелочам.
