### ISSUE TITLE
[LinesCounter] Exception

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#3]
``` C#
try
{
 fileExtension = args[0];
}
catch (Exception)
{
 Console.WriteLine("Please, enter file extension for me");
 fileExtension = Console.ReadLine();
}
```

Вот в наказание за такое издевательство, нагуглите что происходит при выкидывание exception-а, оцените насколько это трудозатратный процесс, расскажите мне, побейте себя веником самостоятельно и исправьте эту конструкцию.

**Comment by dzhana2** [comment]
В ходе исследования было нагуглено, что процесс трудозатратный: когда выкидывается Exception, создается новый объект и на стеке вызовов ищется обработчик для конкретного выброшенного исключения. Делать все это, когда можно обойтись простым if-ом, не очень. 
P.S: Веника нет, как быть?(

**Comment by dzhana2** [comment]
Код исправила.
