### ISSUE TITLE
[Enigma] Кейз

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#5]
``` C#
case "aes":
case "AES":
```

...а так же Aes, aEs, aeS, AEs, aES, AeS... Давайте еще варианты для Рэндала перечислим.
Дарья, откройте для себя волшебные функции ToLower/ToUpper

**Comment by dzhana2** [comment]
Исправлено.

**Comment by pavel-b-novikov** [comment]
угу
