### ISSUE TITLE
[LinesCounter] Константы

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#6]
Какие типы можно объявить как константные? И почему.

**Comment by dzhana2** [comment]
Как const можно объявить встроенные типы (кроме Object).

**Comment by dzhana2** [comment]
Забыла ответить на второй вопрос: значения констант устанавливаются при компиляции, но во время компиляции ссылку на объект мы сформировать не можем => переменную ссылочного типа не получим => все, что не базового типа, константой быть не может.

**Comment by pavel-b-novikov** [comment]
DateTime не базового типа. DateTime может быть константой? :)

**Comment by dzhana2** [comment]
Я не совсем поняла, в чем вопрос -_- Конкретно const мы написать к нему не можем, если очень хочется, чтобы нельзя было изменять(кроме как в конструкторе), надо использовать readonly. Но я думала, что второй случай - это не совсем то, о чем вы меня спросили раньше.

**Comment by pavel-b-novikov** [comment]
А я, если честно, не совсем понял ответ.
"все, что не базового типа". 
В .NET ВСЕ базового типа - типа object. Я предположил что вы имели в виду value/reference type, вот и задал вопрос, чтобы показать что ответ этот неверный.
Ибо как строка вообще reference type, но может быть константной. В то время как вполне себе Value type - DateTime константой быть не может.
Так где же проходит та грань, за которой начинаются const-friendly типы? :)
Утверждение про компиляцию очень верное. От него надо отталкиваться.

**Comment by pavel-b-novikov** [comment]
И чтобы добить ваш мозг окончательно: кстати в VB.NET, который компилируется в CLR и (почти) однозначно транслируется в C#, DateTime таки можно сделать константой, правда выглядит это сильно по-другому.
Этот факт, кстати, можно воспринимать как завуалированную подсказку.

**Comment by dzhana2** [comment]
Заново сформулирую: константными могут быть только встроенные типы (кроме Object - табличка с ними где-то на msdn.microsoft.com), потому что значение константы должно быть нам известно на момент компиляции.

**Comment by pavel-b-novikov** [comment]
Встроенные - это для которых alias существует? 
А вот для enum-а например alias-а не существует, но он может быть константой. Что вы на это скажете?

**Comment by dzhana2** [comment]
Ничего, наверное, не скажу. Я последнее, что нашла - константы вроде должны инициализироваться литералами (числом, логическим выражением, строкой или null). Может какие-нибудь "литеральные типы" есть, и только они могут быть объявлены как константные. Правда, как это к enam применить, я не в курсе, может есть какая-нибудь хитрая схема. Ну или мое предположение неверно. У меня правда больше нет идей, да и вас я, наверное, уже достала глупыми предположениями.

**Comment by pavel-b-novikov** [comment]
Да нет, все верно. 
Есть такие штуки как литеральные типы - это такие классы, состояние любых инстансов которых целиком и полностью описывается строкой кода (терминальным символом, если быть точным). В VB.NET есть терминал для DateTime - выглядит примерно как # 27 May 2015 13:00 #, поэтому его можно вычислить в compile-time и вшить в IL.
Для енамов тут небольшое исключение - его состояние тоже описывается строкой кода целиком и полностью, но терминалом это выражения являться не будет. На этот случай в компиляторе есть соответствующий if.
Такие дела.
