### ISSUE TITLE
[Enigma] Ресурсы

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#7]
Перенесите, пожалуйста, свои бесподобные сообщения в ресурсный файлы (.resx), чтобы их было удобнее читать.

**Comment by dzhana2** [comment]
Исправлено.

**Comment by pavel-b-novikov** [comment]
using (ResourceReader reader = new ResourceReader("Message.resources"))

Да что ж вы все таки сами себе злые буратины? Почему вы с ресурсами общаетесь через ResourceManager или какую другую жесть?
Messages.notArgument сделать не судьба?

**Comment by dzhana2** [comment]
Потому что тот файл, в котором лежал замечательный класс Message, почему-то сгенерировался немного не там, и сначала я про него совсем не знала. Файл нашла, поняла, что так намного проще, исправила.

**Comment by pavel-b-novikov** [comment]
Век живи - век учись
