### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [dzhana2/nsudotnet#8]
В ходе работы шифровальщика диспозится не все, что можно задиспозить. Определите что еще надо уничтожить и оберните в using/вызовите .Dispose

**Comment by dzhana2** [comment]
Исправлено

**Comment by pavel-b-novikov** [comment]
Хм..  _algorithm.Dispose(); в конце метода мне не нравится.
Помните - у вас всегда может вылезти штука вроде ThreadInterruptedException в момент, когда catch для внутреннего исключения отработал, а до  _algorithm.Dispose(); мы еще не дошли.
Мне совесть не позволяет оставить вас в покое с таким подходом.

**Comment by dzhana2** [comment]
Исправила.

**Comment by pavel-b-novikov** [comment]
ну.. так тоже можно. Я ожидал реализации Dispose pattern в классе Cryptographer, но да ладно.
![Image](http://risovach.ru/thumb/upload/200s400/2014/10/mem/vovka_65115148_orig_.jpeg?b4nw7)
